// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDek1m1jIEVGkMO6MTcbPPMRymcoPvWR0w',
    appId: '1:876745083365:web:7ee9da0276ca9c1c47870c',
    messagingSenderId: '876745083365',
    projectId: 'mtnbulkdata',
    authDomain: 'mtnbulkdata.firebaseapp.com',
    storageBucket: 'mtnbulkdata.firebasestorage.app',
    measurementId: 'G-GJ2G9CDQ2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqFx8VjYqrzCvNKf0FYs23qFtZkvDxVA4',
    appId: '1:876745083365:android:1b6eca90f558819947870c',
    messagingSenderId: '876745083365',
    projectId: 'mtnbulkdata',
    storageBucket: 'mtnbulkdata.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG8TQ5r50h6Da6-8AIrUIGSIG_TMlIStY',
    appId: '1:876745083365:ios:e4e27e1ba2072ada47870c',
    messagingSenderId: '876745083365',
    projectId: 'mtnbulkdata',
    storageBucket: 'mtnbulkdata.firebasestorage.app',
    iosClientId: '876745083365-pcgk80f79ctokgonu85b436a9ufundc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cletech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG8TQ5r50h6Da6-8AIrUIGSIG_TMlIStY',
    appId: '1:876745083365:ios:e4e27e1ba2072ada47870c',
    messagingSenderId: '876745083365',
    projectId: 'mtnbulkdata',
    storageBucket: 'mtnbulkdata.firebasestorage.app',
    iosClientId: '876745083365-pcgk80f79ctokgonu85b436a9ufundc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.cletech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDek1m1jIEVGkMO6MTcbPPMRymcoPvWR0w',
    appId: '1:876745083365:web:de21ed0ea7eff76a47870c',
    messagingSenderId: '876745083365',
    projectId: 'mtnbulkdata',
    authDomain: 'mtnbulkdata.firebaseapp.com',
    storageBucket: 'mtnbulkdata.firebasestorage.app',
    measurementId: 'G-ZSLRVDV9EV',
  );
}